### ISSUE TITLE
Start using issue tracker!

### ISSUE THREAD

**Issue by Fxhnd** [Fxhnd/macleod#1]
This could be cool! Axe tree still doesn't do anything?

**Comment by vvicarious** [comment]
Lol. Not don't you worry about DAT.

**Comment by Fxhnd** [comment]
You should see if you can get a linter plug-in for Coda. Pylint would be good

**Comment by vvicarious** [comment]
More like. Atom. CAUSE GITHUB IS GOD

**Comment by Fxhnd** [comment]
Hahaha it looks oddly similar to Sublime 3

**Comment by vvicarious** [comment]
Can people see these commentz?

**Comment by Fxhnd** [comment]
Public repo, so most likely yes

**Comment by vvicarious** [comment]
Hi Torsten!

**Comment by vvicarious** [comment]
Hi Chaw!

**Comment by Fxhnd** [comment]
Ok, think we got the hang of this.
